//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S4_N11_QuanLyKhoSua_4.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BangThongKe
    {
        public string MaSp { get; set; }
        public string TenSP { get; set; }
        public Nullable<int> Số_Lượng_Nhập { get; set; }
        public Nullable<int> Số_Lượng_Xuất { get; set; }
        public Nullable<int> Số_lượng_còn_lại { get; set; }
    }
}
